// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GasControl.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260411233921_AddWaterEntities")]
    partial class AddWaterEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GasControl.Api.Models.Apartment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Apartments");
                });

            modelBuilder.Entity("GasControl.Api.Models.Gas.GasPrice", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PricePerCubicMeter")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("GasPrices");
                });

            modelBuilder.Entity("GasControl.Api.Models.Gas.GasReading", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ApartmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("CurrentReading")
                        .HasColumnType("double precision");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.ToTable("GasReadings");
                });

            modelBuilder.Entity("GasControl.Api.Models.Water.WaterPrice", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PricePerCubicMeter")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("WaterPrices");
                });

            modelBuilder.Entity("GasControl.Api.Models.Water.WaterReading", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ApartmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("CurrentReading")
                        .HasColumnType("double precision");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.ToTable("WaterReadings");
                });

            modelBuilder.Entity("GasControl.Api.Models.Gas.GasReading", b =>
                {
                    b.HasOne("GasControl.Api.Models.Apartment", null)
                        .WithMany()
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GasControl.Api.Models.Water.WaterReading", b =>
                {
                    b.HasOne("GasControl.Api.Models.Apartment", null)
                        .WithMany()
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
